game.ReplicatedStorage.Events.CreateUI.OnServerEvent:Connect(function(player,plr)
	print(player)
	print(plr)
	game.ReplicatedStorage.Events.CreateUI:FireAllClients(plr)
	local hum = player.Character:WaitForChild("HumanoidRootPart")
	hum.CFrame = CFrame.new(game.Workspace.WaitingRoom.Position)
	game.ReplicatedStorage.Events.DisableControls:FireClient(player)
end)

game.ReplicatedStorage.Events.DeleteRoom.OnServerEvent:Connect(function(player,id)
	print(id)
	game.ReplicatedStorage.Events.DeleteRoom:FireAllClients(id)
	local hum = player.Character:WaitForChild("HumanoidRootPart")
	hum.CFrame = CFrame.new(game.Workspace.SpawnLocation.Position)
end)
